### ISSUE TITLE
Document the (main) difference between this plugin and favicons-webpack-plugin

### ISSUE THREAD

**Issue by StephanBijzitter** [brunocodutra/webapp-webpack-plugin#14]
Since this is forked from favicons-webpack-plugin and does support webpack 4 (while favicons-webpack-plugin is working on supporting it), I'm wondering what this plugin offers that the original does not offer.

If it's just increased performance/general maintenance, that's of course also good, but it would be nice to know!

**Comment by brunocodutra** [comment]
My idea is to evolve this project independently from favicons-webpack-plugin, so over time it's expected that they diverge more and more as users (including myself) request new features.

So far I've added support for Webpack 4 and exposed [all configuration options available in Favicons](https://github.com/brunocodutra/webapp-webpack-plugin#advanced-usage), but for a complete and up to date overview of what has been implemented since it was forked you can refer to the [releases changelog](https://github.com/brunocodutra/webapp-webpack-plugin/releases)

Apart from new features, I've also been working on reducing technical debt and [improving test coverage](https://travis-ci.org/brunocodutra/webapp-webpack-plugin).

**Comment by swyxio** [comment]
@brunocodutra  you were just mentioned in https://github.com/redwoodjs/redwood/pull/37#issuecomment-574568220 and i wonder if you depend on `sharp` as well or if anything else has changed in the past 2 years! a quick list of bullet points might help more than combing thru changelogs.

**Comment by brunocodutra** [comment]
Hi @sw-yx, this plugin has been merged back to favicons-webpack-plugin and is now deprecated.
